[package]
name = "rust-guild-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
shuttle-actix-web = "0.52.0"
shuttle-runtime = "0.52.0"
tokio = "1.26.0"
surrealdb = "2.2.1"
serde = { version = "1.0.156", features = ["derive"] }
serde_json = "1.0.89"
serde_urlencoded = "0.7.1"
actix-cors = "0.7.1"
cookie-rs = "0.4.0"
